### ISSUE TITLE
IFeatureCollection has been disposed. Object name: 'Collection'.

### ISSUE THREAD

**Issue by rsantosmello** [nemi-chand/CookieManager#16]
Hi, 
I'm using this package in a net6 code and was getting the error "IFeatureCollection has been disposed. Object name: 'Collection'."

After some investigation, I found that the issue was occurring in the HttpCookie class. The problem was that the _httpContext private field was storing the _httpAccessor.HttpContext is in the construction of the class, but the HttpContext is only valid during the request lifetime, so we can't cache it in a private field.

To fix that, all that I did was change the _httpContext to be an arrow function with will always get the HttpContext from _httpAccessor.HttpContext (private HttpContext _httpContext => _httpAccessor.HttpContext)

`	public class HttpCookie : ICookie
	{
		private readonly IDataProtector _dataProtector;
		private static readonly string Purpose = "CookieManager.Token.v1";
		private readonly CookieManagerOptions _cookieManagerOptions;
		private readonly ChunkingHttpCookie _chunkingHttpCookie;
		private IHttpContextAccessor _httpAccessor;

		/// <summary>
		/// An HttpContext is the context of a single request. It provides access to the request, response properties etc of that single request. You can't cache it, it becomes invalid once that request ends.
		/// See more: https://stackoverflow.com/questions/59963383/session-setstring-method-throws-exception-ifeaturecollection-has-been-disposed
		/// </summary>
		private HttpContext _httpContext => _httpAccessor.HttpContext;

		/// <summary>
		/// External depedenacy of <see cref="IHttpContextAccessor" /> 
		/// </summary>
		/// <param name="httpAccessor">IHttpAccessor</param>
		/// <param name="dataProtectionProvider">data protection provider</param>
		/// <param name="optionAccessor">cookie manager option accessor</param>
		public HttpCookie(IHttpContextAccessor httpAccessor,
			IDataProtectionProvider dataProtectionProvider,
			IOptions<CookieManagerOptions> optionAccessor)
		{
			_httpAccessor = httpAccessor;
			//_httpContext = httpAccessor.HttpContext; //NOT NEEDED ANYMORE
			_dataProtector = dataProtectionProvider.CreateProtector(Purpose);
			_cookieManagerOptions = optionAccessor.Value;
			_chunkingHttpCookie = new ChunkingHttpCookie(optionAccessor);
		}`

Now it is working very well.

It would be good to add this fix to this package.

Thanks

**Comment by nemi-chand** [comment]
@rsantosmello Thanks for raising this issue. The Fix PR has been created. https://github.com/nemi-chand/CookieManager/pull/17
