### ISSUE TITLE
Set cookie failed : Method not found: 'Void Microsoft.Net.Http.Headers.SetCookieHeaderValue..ctor(System.String)

### ISSUE THREAD

**Issue by eddy0223** [nemi-chand/CookieManager#2]
Hello, 
I am getting this exception: Method not found: 'Void Microsoft.Net.Http.Headers.SetCookieHeaderValue..ctor(System.String)'.  anytime I try to set a cookie. 

**Code**
`cookie.Remove(cookiekey);
 cookie.Set(cookiekey, langKey, new CookieOptions() { HttpOnly = true, Expires = DateTime.Now.AddDays(30) });`

**Platform used**:  .net core 2.0

**Comment by eddy0223** [comment]
By the way I have already installed  **Microsoft.AspNetCore.StaticFiles 2.1.1**

**Comment by nemi-chand** [comment]
Hi,
Thanks for reporting issue. you should use pre release version of cookiemanager. 

`Install-Package CookieManager -Version 2.0.0-pre `

let me know if you are still facing issue

**Comment by nemi-chand** [comment]
please update the status @eddy0223

**Comment by jigarce** [comment]
I had same issue resolved using pre release version 2.0 
Thanks,
Jigar

**Comment by nemi-chand** [comment]
@jigarce Thanks for the update
