### ISSUE TITLE
_cookie.Set failed

### ISSUE THREAD

**Issue by MuratGOZCU** [nemi-chand/CookieManager#5]
The first time I run the project, it doesn't weed out the cookies in the morning.

I am using version 2.0.0.

15 minutes after running the project a cookie occurs and the evening until the end of work is not a problem. Can you help with what the problem can be?

"**LanguageIdKey**"  Unable to create

![image](https://user-images.githubusercontent.com/31828822/51162385-fbd21e00-18a6-11e9-850f-14b70825e13c.png)

**Comment by nemi-chand** [comment]
@MuratGOZCU Thanks for reporting the concern . it seem's the requested cookie is no longer exist or expired so make sure that cookie exist and also check for expiration you have set to cookie. 
**ICookieManager** has strongly typed API so no need of conversion. Please use the below sample.

get ICookieManager instance

       ICookieManager _cookieManager;

        public Constructor(ICookieManager cookieManager)
        {
            _cookieManager = cookieManager
        }

use the Get`<T>` API like

`int langKey = _cookieManager.Get<int>('LanguageIdKey') ;`

Hope it helps you

**Comment by nemi-chand** [comment]
I'm closing this issue if you face any issue feel free to reopen.

**Comment by MuratGOZCU** [comment]
thanks for your interest. my problem is solved.

**Comment by nemi-chand** [comment]
@MuratGOZCU great
